### ISSUE TITLE
Unable to set brightness

### ISSUE THREAD

**Issue by willdages** [technobly/Particle-DotStar#5]
I'm receiving an error whenever I try to use the `setBrightness()` method:

```
undefined reference to `Adafruit_DotStar::setBrightness(unsigned char)'
collect2: error: ld returned 1 exit status
```

It's the same error referenced in [this forum post on the original Adafruit library](https://forums.adafruit.com/viewtopic.php?f=47&p=348272) — in that thread an Adafruit support member noted that there was a bug in the library and that it was fixed. I'm not able to understand exactly how they fixed it (a little over my head), but I do see that [the `show()` method in the Adafruit library](https://github.com/adafruit/Adafruit_DotStar/blob/master/Adafruit_DotStar.cpp#L201) does look quite a bit different from this library's. Could you take a look when you get a chance? My LEDs are blinding me 😎. Thanks!

**Comment by technobly** [comment]
I see the issue and have loosely tested a fix.  I'll put this on my list of things to do over the next week.  Please ping me if you don't see this resolved by then :)

**Comment by willdages** [comment]
Hi @technobly just pinging you on this, per your request. Thanks again for taking a look at this issue!

**Comment by technobly** [comment]
@willdages v0.0.4 is live on Build now with the fix.  Thanks!
